"""Create init tables

Revision ID: 20df3f85297d
Revises: 
Create Date: 2022-02-26 18:54:13.018282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20df3f85297d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('lastlogin_dt', sa.DateTime(), nullable=True),
    sa.Column('password_reset_id', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_user_id', sa.Integer(), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('img_url', sa.String(length=10000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mod_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_user_id', sa.Integer(), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mod_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_user_id', sa.Integer(), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mod_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_user_id', sa.Integer(), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mod_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_user_id', sa.Integer(), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mod_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['output.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome')
    op.drop_table('output')
    op.drop_table('activity')
    op.drop_table('stakeholder')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
